/** Domain types shared across all crawler packages. */

export interface Article {
  /** Internal nanoid generated by the crawler when first seen. */
  id: string;
  /** Source identifier, e.g. "daily-dev". */
  source: string;
  /** Stable id from upstream (e.g. daily.dev post id). Combined with `source`
   *  forms the dedupe key. */
  externalId: string;
  /** Original article URL (the link the user wants to read). */
  url: string;
  /** Optional permalink within the source platform (e.g. daily.dev page). */
  permalink: string | null;
  title: string;
  summary: string | null;
  author: string | null;
  /** Publisher / origin site name, e.g. "medium.com". */
  publisher: string | null;
  publisherImage: string | null;
  imageUrl: string | null;
  /** ISO 8601 timestamp from upstream, if known. */
  publishedAt: string | null;
  /** ISO 8601 timestamp this row was crawled. */
  crawledAt: string;
  tags: string[];
  /** JSON.stringify of the full upstream payload for forward compatibility. */
  rawJson: string;
}

export interface CrawlOptions {
  feed: 'popular' | 'search';
  /** Required when `feed === 'search'`. */
  tag?: string;
  /** Reserved for future free-text search; currently unused. */
  query?: string;
  /** Max number of articles to yield. Defaults to 50 in implementations. */
  limit?: number;
}
